### ISSUE TITLE
Dashboard never loads.  Just sits on "Loading"

### ISSUE THREAD

**Issue by EmKayUltra** [cribeiro84/azure-devops-pull-request-hub#45]
Running on Azure DevOps Server.

![image](https://user-images.githubusercontent.com/3580562/69349082-2a4a2380-0c45-11ea-97a2-4d66095ca9a0.png)

Dev tools shows me an error with the API call:

![image](https://user-images.githubusercontent.com/3580562/69349341-93319b80-0c45-11ea-812e-4be0c51f6c45.png)

**Comment by cribeiro84** [comment]
Hi @EmKayUltra,
Currently, the extension requires the version 5.2 of the APIs and your Azure DevOps Server uses 5.1. Do you know if you are able to upgrade the server to a newer version?

This seems to be related to #36 Pull Request. Unfortunately, I did not have enough time to test its impacts by downgrading the extension's version to 5.1.

**Comment by EmKayUltra** [comment]
This is Azure DevOps Server, running the latest update.  I don't think that on-prem DevOps supports API 5.2

**Comment by cribeiro84** [comment]
Fixed #47

**Comment by EmKayUltra** [comment]
It now loads.  However, the hyperlinks on the dashboard don't seem to work.  When I click on a hyperlink to view a PR, I am presented with this:

`{"$id":"1","innerException":null,"message":"The extension 'caribeiro84.pull-request-manager-hub' doesn't contain the requested asset type 'build/undefinedBAC/_git/HUSDMS.Common/pullrequest/166' in version '1.20191123.1'.","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionAssetNotFoundException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionAssetNotFoundException","errorCode":0,"eventId":3000}`

**Comment by cribeiro84** [comment]
I believe I know what happened. I'm now dynamically fetching the organization's URL but I forgot the OnPrem version the URL host is not dev.azure.com. I will work on this week! Sorry for this silly mistake.

**Comment by cribeiro84** [comment]
@EmKayUltra,
I'm releasing a new version with the URL handling for OnPrem instance. Hope this fix the issues you are facing.

**Comment by cribeiro84** [comment]
I'm closing this issue, feel free to reopen in case the problem is not gone yet.

Thanks a lot

**Comment by EmKayUltra** [comment]
With your latest update, we're back to the original problem of it just sitting on loading.

![image](https://user-images.githubusercontent.com/3580562/69886817-d2996100-12b1-11ea-8104-36214578760c.png)

**Comment by cribeiro84** [comment]
Let's reopen it again :-)

It seems now the same error but in a different place. I've introduced a new API call to fetch the organization URL (Cloud version). This call may causing this issue. Let me investigate it again and hopefully I will have a new version pretty soon. 

Sorry for this.

**Comment by cribeiro84** [comment]
@EmKayUltra - I have bad news! I just tried to downgrade the API version to the one that uses the version 5.1 of the Azure DevOps APIs and it's breaking all the extension. Unfortunately, I won't be able to downgrade it at this moment. 

I will be looking for alternatives that I could make it compatible with the OnPrem Azure DevOps.

**Comment by EmKayUltra** [comment]
When you originally downgraded to 5.1 before (to fix the original problem), it worked great and the API error disappeared.  Did that change break the extension for everyone else?

**Comment by cribeiro84** [comment]
I just released a new version (and new features) and also added the error handling when it calls APIs higher than your server supports. Would you be able to test it? I hope I could fix this annoying error for you!

**Comment by EmKayUltra** [comment]
Sure, but I'm not seeing a new version in the Azure marketplace yet.

**Comment by cribeiro84** [comment]
That’s strange. It’s showing for me and also available working on my company’s account.
Would you mind to check again?

**Comment by EmKayUltra** [comment]
Got the update.  Loads again.  Hyperlinks still don't work.

`{"$id":"1","innerException":null,"message":"The extension 'caribeiro84.pull-request-manager-hub' doesn't contain the requested asset type 'build/undefinedMyTeamName/_git/MyRepoName/pullrequest/95' in version '1.20191129.1'.","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionAssetNotFoundException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionAssetNotFoundException","errorCode":0,"eventId":3000}`

**Comment by cribeiro84** [comment]
Is there anything in the console of the browser? How the URL of your server is composed?

Thanks a lot

**Comment by EmKayUltra** [comment]
Nothing of note in the console.  The url that shows that exception (which the individual PR hyperlinks point to) is: https://MY_DOMAIN.com/tfs/_apis/public/gallery/publisher/caribeiro84/extension/pull-request-manager-hub/1.20191129.1/assetbyname/build/undefinedMY_TEAM_NAME/_git/MY_REPO_NAME/pullrequest/95

where the normal hyperlink to access the PR would be https://MY_DOMAIN.com/tfs/MY_COLLECTION_NAME/MY_TEAM_NAME/_git/MY_REPO_NAME/pullrequest/95

**Comment by cribeiro84** [comment]
Got it, I will try to work with this information. My main issue at this moment is the lack of documentation from Azure DevOps Server APIs. I did not find anything related to capture its resources with the internal APIs. :-(

I'm really sorry about it but be sure I'm working to fix it asap.

Thank you so much for providing the additional details.

**Comment by cribeiro84** [comment]
@EmKayUltra - I just released a new version trying to force the TFS URL based on the hostType when it's different of 4 (Cloud) and also from the URL Referrer that comes during the call to the extension. I hope this gets finally fixed :-)

Would you mind (sorry again for asking it) to test?

**Comment by EmKayUltra** [comment]
Unfortunately...

`"$id":"1","innerException":null,"message":"The extension 'caribeiro84.pull-request-manager-hub' doesn't contain the requested asset type 'build/undefinedBAC/_git/EIHub/pullrequest/95' in version '1.20191202.1'.","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionAssetNotFoundException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionAssetNotFoundException","errorCode":0,"eventId":3000}`

**Comment by cribeiro84** [comment]
:-(
Would you be able to run a DEV mode extension to debug it? If so, I can add your organization to the dev mode extension I have (not public) and then you could clone this repo and then run the following commands:

- npm install
- HTTPS=true react-scripts start

If you agree, is it possible to send me (can be privately) your org's name or an account you have so you can download it?

**Comment by cribeiro84** [comment]
In meantime I will try to install the Server version on my azure account and test it. :-)

**Comment by EmKayUltra** [comment]
Hi!  It's been a week, and I wonder if you've had any luck repro'ing.  Unfortunately, I can't run the dev mode extension at the moment.  Although I can probably make that happen in the coming days if it's still needed.

**Comment by cribeiro84** [comment]
Yes, I was able to create my "OnPrem" Azure DevOps Server instance but I'm still debugging it to try to identify the issue. Hopefully in the following days I'll have the fix for it :-)

**Comment by cribeiro84** [comment]
@EmKayUltra - I just released a new version after I created my own AzDevOps Server instance and it seems I was able to fix the URL issue. Could you please test it again? I'm looking forward for the feedback. :-)

**Comment by EmKayUltra** [comment]
Looks like the URL works now 👍 Awesome!

I know you've done a lot of work on this, and I appreciate it.  Is there any way you can change the links so they don't open in a new window?

**Comment by cribeiro84** [comment]
@EmKayUltra I'm really glad to know that! Thanks a lot for the feedback.

About your question, this behavior is intentional because the idea is to highlight the latest PR you clicked in order to facilitate for you to remember where you left (last PR). I have in the backlog new improvements and one of them is to add some Preferences panel for you to configure the behaviors you prefer to have. Stay tuned :-)

**Comment by cribeiro84** [comment]
Also, if you don't mind, please give your rate about this extension. :-)
https://marketplace.visualstudio.com/items?itemName=caribeiro84.pull-request-manager-hub&ssr=false#review-details
